sudo: required

jobs:
  include:
    - stage: test
      env: Type='virus scan'
      script:
        - sudo apt-get install clamav -y
        - sudo freshclam
        - clamscan --quiet -r ./
    - stage: test
      env: Type='eslint'
      language: node_js
      node_js: 8
      script:
        - nvm install 8
        - yarn run eslint
    - stage: test
      env: Type='codecov'
      language: node_js
      node_js: 8
      script:
        - nvm install 8
        - yarn global add codecov
        - codecov